# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=P@ssw0rd
ENV POSTGRES_DB=petopia

# Expose the default PostgreSQL port
EXPOSE 5432
